"use strict";
const $=id=>document.getElementById(id), token=document.querySelector('meta[name="atlas-token"]').content;
history.replaceState({},"",location.pathname);let state={nodes:[],edges:[],depths:{},paths:{},continuation:""};
const headers={"Content-Type":"application/json","X-Atlas-Token":token};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function details(value){const rows=[];for(const [k,v] of Object.entries(value||{})){if(v===undefined)continue;const shown=typeof v==="object"?JSON.stringify(v,null,2):String(v);rows.push(`<dt>${esc(k)}</dt><dd>${shown.length>180?`<code>${esc(shown)}</code>`:esc(shown)}</dd>`)}$("detail").innerHTML=`<dl class="kv">${rows.join("")}</dl>`}
function params(){return{target_path:$("targetPath").value.trim(),target_owner:$("targetOwner").value.trim(),relation:$("relation").value,direction:$("direction").value,depth:Number($("depth").value),max_nodes:Number($("maxNodes").value),max_edges:Number($("maxEdges").value),timeout_ms:30000}}
function continuationOf(data){const t=data.truncation||{};return t.continuation||t.next_continuation||((t.resume||{}).continuation)||""}
function render(){const svg=$("canvas"),nodes=state.nodes,edges=state.edges,w=Math.max(svg.clientWidth,500),h=Math.max(svg.clientHeight,400),pos=new Map();nodes.forEach((n,i)=>{const a=(Math.PI*2*i/Math.max(nodes.length,1))-Math.PI/2,r=Math.min(w,h)*(.12+.24*(i>0));pos.set(n.id,{x:w/2+(i?Math.cos(a)*r:0),y:h/2+(i?Math.sin(a)*r:0)})});let html="";edges.forEach((e,i)=>{const a=pos.get(e.source_id),b=pos.get(e.target_id);if(!a||!b)return;html+=`<g data-edge="${i}"><line class="edge" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><line class="edge-hit" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/></g>`});nodes.forEach((n,i)=>{const p=pos.get(n.id),name=n.name.length>18?n.name.slice(0,17)+"…":n.name;html+=`<g class="node ${i===0?'root':''}" data-node="${i}" transform="translate(${p.x} ${p.y})"><circle r="34"/><text class="label" y="2">${esc(name)}</text><text y="17">${esc(n.kind)}</text></g>`});svg.innerHTML=html;svg.querySelectorAll("[data-node]").forEach(el=>el.onclick=()=>{const n=nodes[Number(el.dataset.node)];details({...n,query_depth:state.depths[n.id],query_path:state.paths[n.id]})});svg.querySelectorAll("[data-edge]").forEach(el=>el.onclick=()=>details(edges[Number(el.dataset.edge)]));$("counts").textContent=`${nodes.length} 节点 · ${edges.length} 边`}
async function run(more=false){const symbol=$("symbol").value.trim();if(!symbol){$("message").textContent="请输入符号。";return}$("run").disabled=true;$("more").disabled=true;$("message").textContent="正在查询…";const p=params();if(more)p.continuation=state.continuation;const started=performance.now();try{const res=await fetch("/api/query",{method:"POST",headers,body:JSON.stringify({query_type:$("type").value,symbol,parameters:p})}),data=await res.json();if(!res.ok)throw new Error(data.message||"查询失败");state.nodes=more?[...state.nodes,...data.nodes.filter(n=>!state.nodes.some(x=>x.id===n.id))]:data.nodes;state.edges=more?[...state.edges,...data.edges]:data.edges;state.depths=more?{...state.depths,...data.depths}:data.depths;state.paths=more?{...state.paths,...data.paths}:data.paths;state.continuation=continuationOf(data);$("more").hidden=!state.continuation;const warnings=data.warnings||[];$("message").className=(data.truncated||warnings.length)?"warning":"";$("message").textContent=data.truncated?`结果已明确截断：${JSON.stringify(data.truncation)}`:warnings.length?warnings.map(w=>w.message).join("\n"):"查询完成，未截断。";$("timing").textContent=`${(performance.now()-started).toFixed(0)} ms`;render();const first=data.nodes[0];details(data.truncated?data.truncation:(first?{...first,query_depth:data.depths[first.id],query_path:data.paths[first.id]}:data))}catch(e){$("message").className="warning";$("message").textContent=e.message}finally{$("run").disabled=false;$("more").disabled=false}}
function fields(){const t=$("type").value;$("relationRow").hidden=!(["callers","callees"].includes(t));$("directionRow").hidden=t!=="impact";$("depthRow").hidden=t!=="impact"}
$("type").onchange=fields;$("run").onclick=()=>run(false);$("more").onclick=()=>run(true);$("symbol").onkeydown=e=>{if(e.key==="Enter")run(false)};fields();
fetch("/api/status",{headers:{"X-Atlas-Token":token}}).then(r=>r.json()).then(s=>{$("project").textContent=`${s.repository} · ${s.language}`;const status=(s.index||{}).status||s.status;$("health").textContent=status}).catch(()=>{$("health").textContent="连接失败"});
